### ISSUE TITLE
Lemmatizer

### ISSUE THREAD

**Issue by vizzerdrix55** [tsproisl/SoMeWeTa#4]
As far as I see, there is no lemmatizer built in in SoMeWeTa. It would be more comfortable to have a third column in the output that contains the lemma.
My output looks like this:

> Geschlagene	ADJA
> 3-Monate	NN
> war	VAFIN

And what I mention is something like this:

> Geschlagene	ADJA	schlagen
> 3-Monate	NN	3-Monate
> war	VAFIN	sein

This feature is supported e.g. by [Texblob](https://textblob.readthedocs.io/en/dev/quickstart.html) (see Words Inflection and Lemmatization) and Stanford CoreNLP. The consideration of the PoS-tags from SoMeWeTa in common lemmatisers (see [this](https://www.machinelearningplus.com/nlp/lemmatization-examples-python/) overview of 7 lemmatisers) can in my eyes only be done with a mapping of the PoS-tags which is time-consuming, non-pythonic and probably leads to a loss of information because of missing corresponding tags in the destination tagset.

**Comment by tsproisl** [comment]
You are right: SoMeWeTa is only a part-of-speech tagger and not a lemmatizer. At the moment, lemmatization is simply not implemented.

Our research group is definitely interested in lemmatization and works towards creating a lemmatizer that performs well on German web and social media texts. So far, we've already created a new gold standard by manually lemmatizing the EmpiriST dataset. For the time being, however, you need to use some other tool for lemmatization.

Regarding the mapping of the POS tags: Since STTS_IBK is an extension or refinement of STTS, a mapping from STTS_IBK to STTS should not be too difficult and can conveniently be represented as a dictionary. You can find such a mapping for example in [Rehbein et al. (2018)](https://www.oeaw.ac.at/fileadmin/subsites/academiaecorpora/PDF/konvens18_03.pdf). With the exception of the new contraction tags (`.+PPER` and `ADVART`), the additional tags of STTS_IBK can be trivially lemmatized, anyway: The lemma should be the surface form in most cases.
